const types = {
  CREATE_USER: "CREATE_USER",
  START_SIGNUP: "START_SIGNUP",
  END_SIGNUP: "END_SIGNUP",
  SEND_CREATE_USER_ERROR: "SEND_CREATE_USER_ERROR",
  REMOVE_CREATE_USER_ERROR: "REMOVE_CREATE_USER_ERROR",
  LOGIN_USER: "LOGIN_USER",
  START_LOGIN: "START_LOGIN",
  END_LOGIN: "END_LOGIN",
  LOGOUT_USER: "LOGOUT_USER",
  SEND_LOGOUT_ERROR: "SEND_LOGOUT_ERROR",
  REMOVE_LOGOUT_ERROR: "REMOVE_LOGOUT_ERROR",
  SEND_LOGIN_ERROR: "SEND_LOGIN_ERROR",
  REMOVE_LOGIN_ERROR: "REMOVE_LOGIN_ERROR",
  GET_TRENDING: "GET_TRENDING",
};

export default types;
