const types = {
  CREATE_USER: "CREATE_USER",
  SEND_CREATE_USER_ERROR: "SEND_CREATE_USER_ERROR",
  REMOVE_CREATE_USER_ERROR: "REMOVE_CREATE_USER_ERROR",
  LOGIN_USER: "LOGIN_USER",
};

export default types;
